### ISSUE TITLE
Laravel 6.1 compatibility

### ISSUE THREAD

**Issue by limenet** [eXolnet/laravel-heartbeat#5]
**Describe the bug**

As no release has been made since #4 was merged, this package is currently preventing upgrades from Laravel 6.0.x to 6.1.x.

**To Reproduce**
1. `composer require laravel/framework:^6.1 exolnet/laravel-heartbeat`
2. Above command will currently fail due to unresolvable package constraints

**Expected behavior**
An upgrade to Laravel 6.1 is possible.

Could you please make a release as soon as possible, e.g. 1.2.1?

Thank you very much for this package, it's fantastic!

**Environment (please complete the following information):**
 - OS: Windows, Ubuntu
 - Framework: Laravel
 - Version: 6.0/6.1

**Comment by xel1045** [comment]
Thanks for reporting. We've released version 1.2.1.

**Comment by limenet** [comment]
Thank you, @xel1045 !
